// Presentation-safe missing child + tester mode hotfix
(() => {
  const PROFILE_KEY='beachGuideMissingChildrenV3';
  const TIP_KEY='beachGuideMissingTipsV3';
  const API='https://beach-guide-missing-child-api.chopyoz1207.workers.dev';
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  let profiles=read(PROFILE_KEY),tips=read(TIP_KEY),mode='choice',draftType=null,draft={};

  const style=document.createElement('style');
  style.textContent=`
  .missing-child-group{background:#fffdfb!important;border-color:#ecc7bd!important}.missing-v3-launch{width:100%;border:0;border-radius:13px;padding:14px;background:#e54843;color:#fff;font-weight:900;font-size:15px;cursor:pointer}.missing-v3-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px}.missing-v3-tab{border:1px solid #c8d8de;background:#fff;color:#355766;border-radius:9px;padding:9px;font-size:10px;font-weight:800}.missing-v3-tab.active{background:#123f69;color:#fff}.missing-v3-count{display:inline-block;margin-left:4px;min-width:16px;padding:1px 5px;border-radius:999px;background:#e54843;color:#fff;font-size:9px}.missing-v3-pane[hidden]{display:none!important}.missing-v3-list{display:grid;gap:9px;margin-top:10px}.missing-v3-empty,.missing-v3-profile{padding:12px;border:1px solid #dbe5e8;border-radius:11px;background:#fff;font-size:10px}.missing-v3-profile h4{margin:0 0 5px;font-size:13px}.missing-v3-profile p{margin:4px 0;color:#5d7580;line-height:1.5}.missing-v3-status{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:9px}.missing-v3-status button{padding:7px 4px;border:1px solid #ccd9de;border-radius:8px;background:#fff;font-size:9px}.missing-v3-status button.active{background:#eef8ff;color:#174f79;border-color:#9fc6df}
  .missing-v3-overlay{position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:12px;background:rgba(8,29,39,.5);overflow:auto;-webkit-overflow-scrolling:touch}.missing-v3-overlay[hidden]{display:none!important}.missing-v3-modal{position:relative;width:min(430px,calc(100vw - 24px));max-height:88dvh;overflow:auto;border-radius:16px;background:#fff;padding:18px;box-shadow:0 18px 60px rgba(0,0,0,.3)}.missing-v3-close{position:sticky;float:right;top:0;z-index:4;width:34px;height:34px;border:0;border-radius:50%;background:#eef3f5;font-size:21px}.missing-v3-title{margin:3px 40px 10px 0;font-size:20px}.missing-v3-sub{font-size:11px;color:#667b83;line-height:1.5}.missing-v3-choice-grid,.missing-v3-form{display:grid;gap:10px;clear:both}.missing-v3-choice{padding:14px;border:1px solid #d6e0e4;border-radius:11px;background:#fff;text-align:left}.missing-v3-choice.report{background:#fff8f7;border-color:#efb1ad}.missing-v3-field{display:block;font-size:10px;font-weight:900}.missing-v3-field input,.missing-v3-field textarea,.missing-v3-field select{display:block;width:100%;margin-top:5px;padding:10px;border:1px solid #cbd8dd;border-radius:9px;font-size:16px}.missing-v3-gender,.missing-v3-time-grid,.missing-v3-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.missing-v3-time-grid{grid-template-columns:repeat(4,1fr);margin-top:6px}.missing-v3-gender button,.missing-v3-time-grid button,.missing-v3-actions button{padding:10px;border:1px solid #cbd8dd;border-radius:9px;background:#fff}.missing-v3-gender button.active,.missing-v3-time-grid button.active{background:#eaf4ff;border-color:#9fc4e5}.missing-v3-primary{background:#e54843!important;color:#fff;border:0!important}.missing-v3-review{clear:both;padding:12px;border-radius:10px;background:#f6f9fa;font-size:11px;line-height:1.7}.missing-v3-success{text-align:center;clear:both}.missing-v3-112{display:block;margin:12px 0 0;padding:12px;border-radius:10px;background:#123f69;color:#fff;text-decoration:none;font-weight:900}.missing-v3-done{width:100%;margin-top:8px;padding:10px}
  .tester-mode .tester-map-pin{display:flex!important}.tester-map-pin{position:relative;align-items:center;gap:5px;padding:8px 10px;border:3px solid #fff;border-radius:11px;box-shadow:0 5px 16px rgba(12,48,68,.35);white-space:nowrap;font-size:11px;font-weight:900}.tester-map-pin.selected{background:#ffbf3c;color:#4a3500}.tester-map-pin.current{background:#1976d2;color:#fff}.tester-mode-switch{position:fixed;z-index:8500;top:12px;left:12px;display:flex;gap:3px;padding:4px;border:1px solid #bfd3da;border-radius:12px;background:#fff;box-shadow:0 5px 18px rgba(17,53,68,.2)}.tester-mode-switch button{border:0;border-radius:8px;padding:7px 9px;background:transparent;color:#536d78;font-size:10px;font-weight:900}.tester-mode-switch button.active{background:#123f69;color:#fff}.tester-mode-badge{position:fixed;z-index:8499;top:58px;left:12px;max-width:250px;padding:8px 10px;border-radius:10px;background:#fff8d9;border:1px solid #e6cc6c;color:#66521c;font-size:9px;font-weight:800}.tester-mode-badge[hidden]{display:none!important}
  @media(max-width:520px){.missing-v3-overlay{align-items:flex-start;padding:7px}.missing-v3-modal{width:100%;max-height:none;margin-bottom:20px;padding:14px}.missing-v3-time-grid{grid-template-columns:1fr 1fr}.missing-v3-status,.missing-v3-actions{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  function counts(){ $('#missingV3Count')&&($('#missingV3Count').textContent=profiles.length); $('#missingV3TipCount')&&($('#missingV3TipCount').textContent=tips.length); }
  function renderLists(){
    const p=$('#missingV3Profiles'),t=$('#missingV3Tips');
    if(p)p.innerHTML=profiles.length?profiles.map(x=>`<article class="missing-v3-profile" data-id="${esc(x.id)}"><h4>${esc(x.name)}</h4><p>${esc(x.gender)} · ${esc(x.age)}세 · ${esc(x.beach||'해변')}</p><p><b>특징</b> ${esc(x.features)}<br><b>마지막 발견</b> ${esc(x.zone)} · ${esc(x.lastSeenTime||'')}</p><div class="missing-v3-status">${['신고 접수','수색 중','수색 완료'].map(s=>`<button data-status="${s}" class="${x.status===s?'active':''}">${s}</button>`).join('')}</div></article>`).join(''):'<div class="missing-v3-empty">등록된 미아가 없습니다.</div>';
    if(t)t.innerHTML=tips.length?tips.map(x=>`<article class="missing-v3-profile"><h4>📍 ${esc(x.name)}</h4><p>${esc(x.gender)} · ${esc(x.age)}세 · ${esc(x.beach||'해변')}</p><p><b>특징</b> ${esc(x.features)}<br><b>발견 구역</b> ${esc(x.zone)}</p></article>`).join(''):'<div class="missing-v3-empty">발견 제보 기록이 없습니다.</div>';
    p?.querySelectorAll('[data-status]').forEach(b=>b.addEventListener('click',()=>{const card=b.closest('[data-id]'),x=profiles.find(v=>v.id===card.dataset.id);if(x){x.status=b.dataset.status;x.updatedAt=Date.now();write(PROFILE_KEY,profiles);renderLists();sync();}})); counts();
  }
  async function sync(){try{await fetch(`${API}/records`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({profiles,tips})})}catch{}}
  async function pull(){try{const r=await fetch(`${API}/records`,{cache:'no-store'});if(r.ok){const d=await r.json();if(Array.isArray(d.profiles))profiles=d.profiles;if(Array.isArray(d.tips))tips=d.tips;write(PROFILE_KEY,profiles);write(TIP_KEY,tips);renderLists();}}catch{}}

  function shell(){const g=$('.missing-child-group');if(!g)return;g.innerHTML=`<section class="emergency-card"><p class="tag">MISSING CHILD</p><h3>미아 신고·발견 제보</h3><p>신고 또는 발견 제보 정보를 정리합니다.</p></section><button id="missingV3Launch" class="missing-v3-launch">🚨 신고·제보하기</button><div class="missing-v3-tabs"><button class="missing-v3-tab active" data-pane="profiles">등록된 미아 <span id="missingV3Count" class="missing-v3-count">0</span></button><button class="missing-v3-tab" data-pane="tips">발견 제보 기록 <span id="missingV3TipCount" class="missing-v3-count">0</span></button></div><div id="missingV3ProfilesPane"><div id="missingV3Profiles" class="missing-v3-list"></div></div><div id="missingV3TipsPane" hidden><div id="missingV3Tips" class="missing-v3-list"></div></div><div id="missingV3Overlay" class="missing-v3-overlay" hidden><section class="missing-v3-modal"><button id="missingV3Close" class="missing-v3-close">×</button><div id="missingV3Body"></div></section></div>`;}
  const zone=()=>$('#selectedAddress')?.textContent?.replace(/\s+/g,' ').trim()||'HD-D6 구역';
  const beach=()=>$('#beachSelect')?.selectedOptions?.[0]?.textContent?.split(' · ')[0]||'해운대해수욕장';
  const lastLabel=()=>draft.lastSeenMode==='custom'&&draft.custom?draft.custom:(Number(draft.minutes??5)===0?'방금 전':`${Number(draft.minutes??5)}분 전`);
  function renderModal(){const b=$('#missingV3Body');if(!b)return;if(mode==='choice')b.innerHTML=`<h2 class="missing-v3-title">상황에 맞는 항목을 선택해주세요.</h2><p class="missing-v3-sub">미아 신고 또는 발견 제보를 선택하세요.</p><div class="missing-v3-choice-grid"><button class="missing-v3-choice report" data-a="report"><strong>🚨 미아 신고</strong></button><button class="missing-v3-choice" data-a="tip"><strong>📍 발견 제보</strong></button></div>`;else if(mode==='form'){const report=draftType==='report';b.innerHTML=`<h2 class="missing-v3-title">${report?'미아 신고':'발견 제보'} 정보 입력</h2><form id="missingForm" class="missing-v3-form"><label class="missing-v3-field">이름<input id="mn" required value="${esc(draft.name||'')}"></label><div class="missing-v3-field">성별<div class="missing-v3-gender"><button type="button" data-g="남자" class="${draft.gender==='남자'?'active':''}">남자</button><button type="button" data-g="여자" class="${draft.gender==='여자'?'active':''}">여자</button></div></div><label class="missing-v3-field">나이<select id="ma"><option value="">선택</option>${Array.from({length:19},(_,i)=>`<option ${String(draft.age)===String(i)?'selected':''}>${i}</option>`).join('')}</select></label><label class="missing-v3-field">특징<textarea id="mf" required>${esc(draft.features||'')}</textarea></label>${report?`<div class="missing-v3-field">마지막으로 본 시간<div class="missing-v3-time-grid">${[[0,'방금 전'],[5,'5분 전'],[10,'10분 전'],[30,'30분 전']].map(([n,l])=>`<button type="button" data-min="${n}" class="${draft.minutes===n?'active':''}">${l}</button>`).join('')}</div></div>`:''}<label class="missing-v3-field">${report?'마지막으로 본 구역':'발견 구역'}<input id="mz" required value="${esc(draft.zone||zone())}"></label><div class="missing-v3-actions"><button type="button" data-a="back">이전</button><button class="missing-v3-primary" type="submit">${report?'신고하기':'제보하기'}</button></div></form>`;}else if(mode==='review')b.innerHTML=`<h2 class="missing-v3-title">최종 확인</h2><div class="missing-v3-review">이름: ${esc(draft.name)}<br>성별: ${esc(draft.gender)} · ${esc(draft.age)}세<br>특징: ${esc(draft.features)}<br>구역: ${esc(draft.zone)}${draftType==='report'?`<br>마지막 목격: ${esc(lastLabel())}`:''}</div><div class="missing-v3-actions" style="margin-top:10px"><button data-a="edit">취소하기</button><button class="missing-v3-primary" data-a="submit">${draftType==='report'?'신고하기':'제보하기'}</button></div>`;else b.innerHTML=`<div class="missing-v3-success"><h2>접수되었습니다.</h2><a class="missing-v3-112" href="tel:112">112 경찰 신고 전화 연결</a><button class="missing-v3-done" data-a="done">닫기</button></div>`;bindModal();}
  function bindModal(){document.querySelectorAll('[data-a]').forEach(x=>x.addEventListener('click',()=>{const a=x.dataset.a;if(a==='report'||a==='tip'){draftType=a;draft={zone:zone(),minutes:5};mode='form';renderModal();}else if(a==='back'){mode='choice';renderModal();}else if(a==='edit'){mode='form';renderModal();}else if(a==='submit'){const now=Date.now(),obj={id:`${draftType}-${now}`,createdAt:now,updatedAt:now,name:draft.name,gender:draft.gender,age:Number(draft.age),features:draft.features,zone:draft.zone,beach:beach()};if(draftType==='report')profiles.unshift({...obj,lastSeenTime:lastLabel(),status:'신고 접수'});else tips.unshift({...obj,type:'발견 제보'});write(PROFILE_KEY,profiles);write(TIP_KEY,tips);renderLists();sync();mode='success';renderModal();}else if(a==='done')close();}));document.querySelectorAll('[data-g]').forEach(x=>x.addEventListener('click',()=>{draft.gender=x.dataset.g;renderModal();}));document.querySelectorAll('[data-min]').forEach(x=>x.addEventListener('click',()=>{draft.minutes=Number(x.dataset.min);renderModal();}));$('#missingForm')?.addEventListener('submit',e=>{e.preventDefault();draft={...draft,name:$('#mn').value.trim(),age:$('#ma').value,features:$('#mf').value.trim(),zone:$('#mz').value.trim()};if(!draft.name||!draft.gender||draft.age===''||!draft.features||!draft.zone){alert('입력하지 않은 항목을 확인해주세요.');return;}mode='review';renderModal();});}
  function open(){mode='choice';draft={};$('#missingV3Overlay').hidden=false;document.body.style.overflow='hidden';renderModal();}
  function close(){$('#missingV3Overlay').hidden=true;document.body.style.overflow='';}

  // Robust presentation tester. Uses one exact point for both demo states.
  let tester=false,selOverlay=null,curOverlay=null;
  const DEMO={lat:35.15882,lng:129.16028};
  function clearDemo(){try{selOverlay?.setMap(null);curOverlay?.setMap(null);selOverlay=curOverlay=null;if(typeof myLocationMarker!=='undefined'&&myLocationMarker)myLocationMarker.setMap(null);}catch{}}
  function makePin(text,kind,xAnchor){const el=document.createElement('div');el.className=`tester-map-pin ${kind}`;el.textContent=text;return new kakao.maps.CustomOverlay({map:kakaoMap,position:new kakao.maps.LatLng(DEMO.lat,DEMO.lng),content:el,xAnchor,yAnchor:1.35,zIndex:120});}
  function showDemo(){if(!tester)return;try{clearDemo();const cell=typeof geoGrid!=='undefined'?geoGrid.get('D6'):null;if(cell&&typeof selectGeoCell==='function')selectGeoCell('D6',cell.polygon);selOverlay=makePin('선택 위치 HD-D6','selected',1.05);curOverlay=makePin('내 현재 위치 · TEST','current',-0.05);if(typeof myLocationMarker!=='undefined')myLocationMarker=new kakao.maps.Marker({map:kakaoMap,position:new kakao.maps.LatLng(DEMO.lat,DEMO.lng),title:'발표용 현재 위치'});kakaoMap.panTo(new kakao.maps.LatLng(DEMO.lat,DEMO.lng));$('#selectedAddress')&&($('#selectedAddress').innerHTML='HD-D6 <em>구역</em>');$('#mapNotice')&&($('#mapNotice').textContent='TESTER MODE · 선택 위치와 현재 위치를 같은 HD-D6 구역에서 시연 중입니다. 실제 GPS는 사용하지 않습니다.');}catch(e){$('#mapNotice')&&($('#mapNotice').textContent='TESTER MODE · HD-D6 위치 시연 중입니다.');}}
  function testerUI(){const box=document.createElement('div');box.className='tester-mode-switch';box.innerHTML='<button id="testerNormal" class="active">일반 모드</button><button id="testerDemo">TESTER</button>';document.body.appendChild(box);const badge=document.createElement('div');badge.id='testerBadge';badge.className='tester-mode-badge';badge.hidden=true;badge.textContent='발표용 위치 시연 중 · 실제 GPS와 신고 데이터는 변경하지 않습니다.';document.body.appendChild(badge);$('#testerDemo').onclick=()=>{tester=true;document.documentElement.classList.add('tester-mode');$('#testerDemo').classList.add('active');$('#testerNormal').classList.remove('active');badge.hidden=false;setTimeout(showDemo,100);setTimeout(showDemo,500)};$('#testerNormal').onclick=()=>{tester=false;document.documentElement.classList.remove('tester-mode');$('#testerNormal').classList.add('active');$('#testerDemo').classList.remove('active');badge.hidden=true;clearDemo();};document.addEventListener('click',e=>{if(tester&&e.target.closest?.('#locateMe')){e.preventDefault();e.stopImmediatePropagation();showDemo();}},true);}

  function init(){shell();renderLists();counts();$('#missingV3Launch').onclick=open;$('#missingV3Close').onclick=close;$('#missingV3Overlay').addEventListener('click',e=>{if(e.target.id==='missingV3Overlay')close();});document.querySelectorAll('.missing-v3-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.missing-v3-tab').forEach(x=>x.classList.toggle('active',x===b));$('#missingV3ProfilesPane').hidden=b.dataset.pane!=='profiles';$('#missingV3TipsPane').hidden=b.dataset.pane!=='tips';});testerUI();pull();setInterval(pull,30000);}
  if(document.readyState==='loading')window.addEventListener('load',init,{once:true});else init();
})();