// Multi-beach compatibility + safety UI.
(() => {
  const BEACH = {
    haeundae:{name:"해운대해수욕장",prefix:"HD",lat:35.1587,lng:129.1604,ripCode:"HAE"},
    gwangalli:{name:"광안리해수욕장",prefix:"GW",lat:35.15089,lng:129.11908,wayId:107642460,ripCode:null},
    songjeong:{name:"송정해수욕장",prefix:"SJ",lat:35.18046,lng:129.20335,wayId:null,ripCode:"SONGJUNG"},
    songdo:{name:"송도해수욕장",prefix:"SD",lat:35.07564,lng:129.01881,wayId:474957001,ripCode:null}
  };
  const OVERPASS=["https://overpass-api.de/api/interpreter","https://overpass.private.coffee/api/interpreter","https://overpass.kumi.systems/api/interpreter"];
  const RIP_WORKER="https://beach-guide-rip-current-api.chopyoz1207.workers.dev";
  const GRID=10,CACHE_MS=30*24*60*60*1000;
  let cells=[],selectedCell=null,selectedGridId=null,selectedPoint=null,ignoreMapClickUntil=0,facilityOverlays=[],loadVersion=0;
  const beachKey=()=>document.querySelector("#beachSelect")?.value||"haeundae";
  const current=()=>BEACH[beachKey()]||BEACH.haeundae;
  const isHaeundae=()=>beachKey()==="haeundae";

  function alpha(index){let n=index+1,s="";while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
  function normalizeHD(text){const raw=String(text||"").replace(/구역/g,"").replace(/·.*$/g,"").trim();let m=raw.match(/^HD-([A-Z]+)0*(\d+)$/i);if(m)return`HD-${m[1].toUpperCase()}${Number(m[2])}`;m=raw.match(/^([A-Z]+)0*(\d+)$/i);if(m)return`HD-${m[1].toUpperCase()}${Number(m[2])}`;m=raw.match(/^(\d+)-([A-Z]+)$/i);return m?`HD-${m[2].toUpperCase()}${Number(m[1])}`:"";}
  function clearCells(){cells.forEach(p=>p.setMap(null));cells=[];selectedCell=null;selectedGridId=null;}
  function clearFacilities(){facilityOverlays.forEach(o=>o.setMap(null));facilityOverlays=[];}
  function projection(origin){const ml=111320,mg=111320*Math.cos(origin.lat*Math.PI/180);return{toXY:p=>({x:(p.lng-origin.lng)*mg,y:(p.lat-origin.lat)*ml}),toGeo:p=>({lat:origin.lat+p.y/ml,lng:origin.lng+p.x/mg})};}
  function inside(p,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<((b.x-a.x)*(p.y-a.y))/(b.y-a.y)+a.x)yes=!yes;}return yes;}
  function axes(points){const cx=points.reduce((s,p)=>s+p.x,0)/points.length,cy=points.reduce((s,p)=>s+p.y,0)/points.length;let xx=0,yy=0,xy=0;points.forEach(p=>{const dx=p.x-cx,dy=p.y-cy;xx+=dx*dx;yy+=dy*dy;xy+=dx*dy;});const angle=.5*Math.atan2(2*xy,xx-yy);let u={x:Math.cos(angle),y:Math.sin(angle)};if(u.x<0)u={x:-u.x,y:-u.y};return{c:{x:cx,y:cy},u,v:{x:-u.y,y:u.x}};}
  const toFrame=(p,a)=>{const dx=p.x-a.c.x,dy=p.y-a.c.y;return{x:dx*a.u.x+dy*a.u.y,y:dx*a.v.x+dy*a.v.y};};
  const fromFrame=(p,a)=>({x:a.c.x+p.x*a.u.x+p.y*a.v.x,y:a.c.y+p.x*a.u.y+p.y*a.v.y});
  const cacheKey=cfg=>`actualBeachBoundary:${cfg.prefix}:v6`;
  function cachedBoundary(cfg){try{const v=JSON.parse(localStorage.getItem(cacheKey(cfg))||"null");return v&&Array.isArray(v.boundary)&&Date.now()-v.savedAt<CACHE_MS?v.boundary:null;}catch{return null;}}
  function saveBoundary(cfg,b){try{localStorage.setItem(cacheKey(cfg),JSON.stringify({savedAt:Date.now(),boundary:b}));}catch{}}
  async function overpass(q){let last;for(const endpoint of OVERPASS){try{const c=new AbortController(),t=setTimeout(()=>c.abort(),10000),r=await fetch(`${endpoint}?data=${encodeURIComponent(q)}`,{headers:{Accept:"application/json"},signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error();const d=await r.json();if(Array.isArray(d.elements))return d;}catch(e){last=e;}}throw last||new Error();}
  function centre(e){const g=e.geometry||[];if(!g.length)return null;const s=g.reduce((a,p)=>({lat:a.lat+p.lat,lng:a.lng+p.lon}),{lat:0,lng:0});return{lat:s.lat/g.length,lng:s.lng/g.length};}
  function d2(a,b){const y=(a.lat-b.lat)*111320,x=(a.lng-b.lng)*111320*Math.cos(a.lat*Math.PI/180);return x*x+y*y;}
  async function boundary(cfg){const hit=cachedBoundary(cfg);if(hit)return hit;const q=cfg.wayId?`[out:json][timeout:18];way(${cfg.wayId});out geom tags;`:`[out:json][timeout:18];way(around:1800,${cfg.lat},${cfg.lng})["natural"="beach"];out geom tags;`;const d=await overpass(q);let way;if(cfg.wayId)way=d.elements.find(e=>e.type==="way"&&e.id===cfg.wayId);else{const ways=d.elements.filter(e=>e.type==="way"&&Array.isArray(e.geometry)&&e.geometry.length>=4);way=ways.map(w=>{const name=w.tags?.name||w.tags?.["name:ko"]||"";return{w,score:d2(centre(w)||cfg,cfg)-(name.includes("송정")?1e12:0)};}).sort((a,b)=>a.score-b.score)[0]?.w;}if(!way?.geometry?.length)throw new Error();const b=way.geometry.map(p=>({lat:p.lat,lng:p.lon}));saveBoundary(cfg,b);return b;}
  function gridNote(){const card=document.querySelector(".location-card");if(!card)return null;let el=card.querySelector(".multi-beach-grid-note");if(!el){el=document.createElement("p");el.className="multi-beach-grid-note";el.style.cssText="margin:10px 0 0;padding:9px 10px;border-radius:9px;background:#f4fafb;color:#60787e;font-size:10px;line-height:1.5";card.appendChild(el);}el.hidden=isHaeundae();return el;}
  function showSelection(id,point){const cfg=current(),sel=document.querySelector("#selectedAddress"),panel=document.querySelector("#panelAddress"),desc=document.querySelector(".location-card p");if(sel)sel.innerHTML=`${id} <em>구역</em>`;if(panel)panel.innerHTML=`${id} 구역 <small>· 10m × 10m</small>`;if(desc)desc.textContent=`${cfg.name} 모래사장`;selectedGridId=id;selectedPoint=point;window.setNotice?.(`${cfg.name} ${id} 구역을 선택했어요.`);}
  function selectCell(id,polygon,point){ignoreMapClickUntil=Date.now()+450;if(selectedCell)selectedCell.setOptions({fillOpacity:.05,strokeColor:"#237a8b",strokeWeight:1});selectedCell=polygon;polygon.setOptions({fillOpacity:.52,fillColor:"#f6b73c",strokeColor:"#d76b00",strokeWeight:2});showSelection(id,point);}
  async function drawGrid(version){clearCells();if(isHaeundae()||!window.kakaoMap||!window.kakao?.maps)return;const cfg=current(),note=gridNote();if(note)note.textContent=`${cfg.name} 실제 모래사장 경계를 불러오는 중입니다.`;try{const b=await boundary(cfg);if(version!==loadVersion||isHaeundae())return;const origin=b.reduce((a,p)=>({lat:a.lat+p.lat/b.length,lng:a.lng+p.lng/b.length}),{lat:0,lng:0}),proj=projection(origin),local=b.map(proj.toXY),ax=axes(local),framed=local.map(p=>toFrame(p,ax)),minX=Math.floor(Math.min(...framed.map(p=>p.x))/GRID)*GRID,maxX=Math.ceil(Math.max(...framed.map(p=>p.x))/GRID)*GRID,minY=Math.floor(Math.min(...framed.map(p=>p.y))/GRID)*GRID,maxY=Math.ceil(Math.max(...framed.map(p=>p.y))/GRID)*GRID;let count=0,row=0;for(let y=minY;y<maxY;y+=GRID,row++){let col=0;for(let x=minX;x<maxX;x+=GRID,col++){const fc=[{x,y},{x:x+GRID,y},{x:x+GRID,y:y+GRID},{x,y:y+GRID}],cc={x:x+5,y:y+5};if(!inside(cc,framed)||!fc.every(p=>inside(p,framed)))continue;const corners=fc.map(p=>proj.toGeo(fromFrame(p,ax))),c=proj.toGeo(fromFrame(cc,ax)),id=`${cfg.prefix}-${alpha(row)}${col+1}`,poly=new kakao.maps.Polygon({map:kakaoMap,path:corners.map(p=>new kakao.maps.LatLng(p.lat,p.lng)),strokeWeight:1,strokeColor:"#237a8b",strokeOpacity:.72,fillColor:"#70d1d2",fillOpacity:.05});kakao.maps.event.addListener(poly,"click",()=>selectCell(id,poly,c));cells.push(poly);count++;}}if(note)note.textContent=`${cfg.prefix} 체계의 10m 안내격자 ${count.toLocaleString()}개를 실제 모래사장 경계 안에 표시했습니다.`;window.setNotice?.(`${cfg.name} 실제 모래사장 경계 안에만 10m 안내격자를 표시했어요.`);}catch{if(note)note.textContent=`${cfg.name} 실제 모래사장 경계를 불러오지 못해 격자를 표시하지 않았습니다.`;window.setNotice?.(`${cfg.name} 모래사장 경계 연결에 실패했어요. 잠시 후 다시 선택해 주세요.`);}}
  function repairHD(){if(!isHaeundae())return;const sel=document.querySelector("#selectedAddress"),panel=document.querySelector("#panelAddress"),desc=document.querySelector(".location-card p"),id=normalizeHD(sel?.textContent||panel?.textContent||"");if(desc)desc.textContent="해운대해수욕장 모래사장";if(id){if(sel&&!sel.textContent.trim().startsWith("HD-"))sel.innerHTML=`${id} <em>구역</em>`;if(panel&&!panel.textContent.trim().startsWith(id))panel.innerHTML=`${id} 구역 <small>· 10m × 10m</small>`;}const n=gridNote();if(n)n.hidden=true;}
  function resetUI(){const cfg=current(),title=document.querySelector(".panel-head h2"),desc=document.querySelector(".location-card p");document.title=`해변가이드 | ${cfg.name} 안전 지도`;if(title)title.textContent=`${cfg.name} 안전 안내`;if(desc)desc.textContent=`${cfg.name} 모래사장`;if(isHaeundae())repairHD();else{const s=document.querySelector("#selectedAddress"),p=document.querySelector("#panelAddress");if(s)s.innerHTML=`격자를 선택하세요 <em>${cfg.name}</em>`;if(p)p.innerHTML=`격자를 선택하세요 <small>· 10m × 10m</small>`;gridNote();}}
  const fmt=p=>`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}`;
  async function copyOther(e){if(isHaeundae())return;e.preventDefault();e.stopImmediatePropagation();const cfg=current(),id=selectedGridId||"지도 위치",p=selectedPoint||cfg,text=`${cfg.name} ${id} ${fmt(p)}`;try{await navigator.clipboard.writeText(text);window.setNotice?.(`${id} 위치를 복사했어요.`);}catch{window.setNotice?.(text);}}
  async function shareOther(e){if(isHaeundae())return;e.preventDefault();e.stopImmediatePropagation();const cfg=current(),id=selectedGridId||"지도 위치",p=selectedPoint||cfg,text=`${cfg.name} 만남 위치: ${id} · ${fmt(p)}`;try{if(navigator.share)await navigator.share({title:`${cfg.name} 만남 위치`,text,url:location.href});else await navigator.clipboard.writeText(`${text}\n${location.href}`);}catch(err){if(err.name!=="AbortError")window.setNotice?.("공유하지 못했어요.");}}
  function locateOther(e){if(isHaeundae())return;e.preventDefault();e.stopImmediatePropagation();const b=e.currentTarget;if(!navigator.geolocation){window.setNotice?.("GPS를 사용할 수 없어요.");return;}b.disabled=true;b.textContent="현재 위치를 확인하고 있어요…";navigator.geolocation.getCurrentPosition(({coords})=>{selectedPoint={lat:coords.latitude,lng:coords.longitude};const pos=new kakao.maps.LatLng(selectedPoint.lat,selectedPoint.lng);if(window.myLocationMarker)myLocationMarker.setMap(null);window.myLocationMarker=new kakao.maps.Marker({map:kakaoMap,position:pos,title:"내 현재 위치"});kakaoMap.panTo(pos);b.disabled=false;b.innerHTML="내 현재 위치 지도에서 확인 <span>⌖</span>";window.setNotice?.(`${current().name} 주변에서 현재 GPS 위치를 표시했어요.`);},()=>{b.disabled=false;b.innerHTML="내 현재 위치 지도에서 확인 <span>⌖</span>";window.setNotice?.("위치 권한을 허용해 주세요.");},{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
  async function publicFacilities(version){clearFacilities();if(isHaeundae())return;const cfg=current(),q=`[out:json][timeout:12];(nwr(around:1200,${cfg.lat},${cfg.lng})["amenity"="toilets"];nwr(around:1200,${cfg.lat},${cfg.lng})["amenity"="shower"];nwr(around:1200,${cfg.lat},${cfg.lng})["amenity"="parking"];);out center tags;`;let d=null;for(const endpoint of OVERPASS){try{const r=await fetch(`${endpoint}?data=${encodeURIComponent(q)}`);if(r.ok){d=await r.json();break;}}catch{}}if(!d||version!==loadVersion||isHaeundae())return;(d.elements||[]).slice(0,40).forEach(el=>{const p=el.lat!=null?{lat:el.lat,lng:el.lon}:el.center?{lat:el.center.lat,lng:el.center.lon}:null;if(!p)return;const a=el.tags?.amenity,icon=a==="toilets"?"🚻":a==="shower"?"🚿":"🅿",name=el.tags?.name||el.tags?.["name:ko"]||(a==="toilets"?"화장실":a==="shower"?"샤워 시설":"주차장"),btn=document.createElement("button");btn.type="button";btn.className="map-facility-label";btn.textContent=icon;btn.addEventListener("click",()=>window.setNotice?.(`${name} · 공개 지도 시설 정보`));facilityOverlays.push(new kakao.maps.CustomOverlay({map:kakaoMap,position:new kakao.maps.LatLng(p.lat,p.lng),yAnchor:1,content:btn}));});}
  async function loadSongjeongRip(version){if(beachKey()!=="songjeong")return;try{const r=await fetch(`${RIP_WORKER}/rip-current?beachCode=SONGJUNG`);if(!r.ok)throw new Error();const d=await r.json();if(version!==loadVersion||beachKey()!=="songjeong")return;const items=Array.isArray(d.items)?d.items:[],latest=items.at(-1);if(!latest)throw new Error();const level=String(latest.lastScrCn||"관심").trim()||"관심",rank={관심:["🟢","관심"],주의:["🟡","주의"],경계:["🟠","경계"],위험:["🔴","위험"]}[level]||["🟢",level];document.querySelector("#ripCurrentLight").textContent=rank[0];document.querySelector("#ripCurrentLevel").textContent=`${rank[1]} · 송정해수욕장 이안류 지수`;document.querySelector("#ripCurrentStatus").textContent=`국립해양조사원 공식 이안류 지수 ${rank[1]} 단계입니다.`;}catch{const el=document.querySelector("#ripCurrentLevel");if(el)el.textContent="공식 정보 확인 필요";}}
  function onBeachChange(){const version=++loadVersion;clearCells();clearFacilities();selectedPoint=null;selectedGridId=null;resetUI();if(isHaeundae()){setTimeout(repairHD,60);setTimeout(repairHD,300);return;}setTimeout(()=>{if(version===loadVersion&&!isHaeundae()){drawGrid(version);publicFacilities(version);loadSongjeongRip(version);}},120);}
  function init(){document.querySelector("#beachSelect")?.addEventListener("change",onBeachChange);document.querySelector("#copyAddress")?.addEventListener("click",copyOther,true);document.querySelector("#shareMeeting")?.addEventListener("click",shareOther,true);document.querySelector("#locateMe")?.addEventListener("click",locateOther,true);if(window.kakaoMap&&window.kakao?.maps)kakao.maps.event.addListener(kakaoMap,"click",e=>{if(isHaeundae()||Date.now()<ignoreMapClickUntil)return;selectedGridId=null;selectedPoint={lat:e.latLng.getLat(),lng:e.latLng.getLng()};const cfg=current(),s=document.querySelector("#selectedAddress");if(s)s.innerHTML=`지도 위치 <em>${cfg.name}</em>`;});const s=document.querySelector("#selectedAddress");if(s)new MutationObserver(()=>{if(isHaeundae()&&normalizeHD(s.textContent)&&!s.textContent.trim().startsWith("HD-"))repairHD();}).observe(s,{childList:true,subtree:true,characterData:true});resetUI();}
  if(document.readyState==="complete")init();else window.addEventListener("load",init,{once:true});
})();

// Weather and marine-safety modal.
(() => {
  let active="overview";
  const ITEMS=[
    {key:"weather",icon:"☀️",label:"날씨",selector:".weather-card",desc:"기온 · 강수 · 바람"},
    {key:"safety",icon:"🚦",label:"안전지수",selector:".safety-index-card",desc:"현재 조건 종합 판정"},
    {key:"condition",icon:"🌊",label:"해변상태",selector:".condition-card",desc:"기상·조석·이안류 해석"},
    {key:"rip",icon:"⚠️",label:"이안류",selector:".rip-current-card",desc:"공식 이안류 위험 정보"},
    {key:"tide",icon:"↕️",label:"조석",selector:".tide-card",desc:"만조 · 간조 시각"}
  ];
  function styles(){if(document.querySelector("#safetyModalStyles"))return;const s=document.createElement("style");s.id="safetyModalStyles";s.textContent=`.environment-group{border:0!important;background:transparent!important;overflow:visible!important}.environment-group>summary{display:none!important}.environment-group .environment-body{padding:0!important}.safety-launch-card{border:1px solid #bddde4;border-radius:15px;background:#f7fcfd;padding:15px}.safety-launch-card .tag,.safety-modal-head .tag{margin:0;color:#087698;font-size:10px;font-weight:900;letter-spacing:.14em}.safety-launch-card h3{margin:6px 0 5px;color:#123b50;font-size:16px}.safety-launch-card p,.safety-modal-head p{margin:0;color:#667f87;font-size:10px;line-height:1.55}.safety-launch-button{width:100%;margin-top:11px;border:0;border-radius:11px;padding:12px;background:#0b7896;color:#fff;font-weight:900;font-size:12px;cursor:pointer}.safety-modal-overlay{position:fixed;inset:0;z-index:99990;display:grid;place-items:center;padding:16px;background:rgba(7,28,39,.48);backdrop-filter:blur(2px)}.safety-modal-overlay[hidden]{display:none!important}.safety-modal{position:relative;width:min(500px,calc(100vw - 28px));max-height:min(86vh,780px);overflow:auto;box-sizing:border-box;border-radius:18px;background:#fff;box-shadow:0 20px 60px rgba(0,0,0,.3);padding:20px}.safety-modal-close{position:absolute;right:11px;top:11px;width:34px;height:34px;border:0;border-radius:50%;background:#f1f5f6;color:#284c58;font-size:21px;cursor:pointer}.safety-modal-head h2{margin:4px 42px 6px 0;color:#123b50;font-size:20px}.safety-choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:15px}.safety-choice{border:1px solid #d5e2e6;border-radius:12px;background:#fff;padding:12px;text-align:left;cursor:pointer}.safety-choice:hover{background:#f7fbfc}.safety-choice b{display:block;color:#173f50;font-size:12px}.safety-choice span{display:block;margin-top:4px;color:#70868d;font-size:9px}.safety-choice-icon{font-size:18px;margin-bottom:5px}.safety-modal-content{margin-top:14px}.safety-modal-content>*{margin-top:0!important}.safety-modal-back{width:100%;margin-top:12px;border:1px solid #bfd5dc;border-radius:10px;padding:10px;background:#fff;color:#315968;font-weight:800;cursor:pointer}.safety-modal-helper{margin:12px 0 0;padding:9px;border-radius:9px;background:#f6fafb;color:#6a8087;font-size:9px;line-height:1.5}@media(max-width:520px){.safety-modal{max-height:90vh;padding:17px}.safety-choice-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}
  function setup(){const group=document.querySelector(".environment-group"),body=group?.querySelector(".environment-body");if(!group||!body||document.querySelector("#safetyModalOverlay"))return;styles();const cards={};ITEMS.forEach(i=>{const el=body.querySelector(i.selector);if(el)cards[i.key]=el;});const launch=document.createElement("section");launch.className="safety-launch-card";launch.innerHTML=`<p class="tag">WEATHER · MARINE SAFETY</p><h3>기상·해양 안전 정보</h3><p>날씨, 안전지수, 해변상태, 이안류, 조석 중 필요한 정보만 선택해서 확인하세요.</p><button id="openSafetyModal" class="safety-launch-button" type="button">안전 정보 선택해서 보기</button>`;body.innerHTML="";body.appendChild(launch);const overlay=document.createElement("div");overlay.id="safetyModalOverlay";overlay.className="safety-modal-overlay";overlay.hidden=true;overlay.innerHTML=`<section class="safety-modal" role="dialog" aria-modal="true"><button id="closeSafetyModal" class="safety-modal-close" type="button" aria-label="닫기">×</button><div id="safetyModalInner"></div></section>`;document.body.appendChild(overlay);const stash=document.createElement("div");stash.id="safetyLiveCardStash";stash.hidden=true;Object.values(cards).forEach(c=>stash.appendChild(c));document.body.appendChild(stash);const beachLabel=()=>document.querySelector("#beachSelect")?.selectedOptions?.[0]?.textContent?.split(" · ")[0]||"선택한 해변";
    function choice(){active="overview";const inner=document.querySelector("#safetyModalInner");inner.innerHTML=`<div class="safety-modal-head"><p class="tag">WEATHER · MARINE SAFETY</p><h2>어떤 정보를 확인할까요?</h2><p>${beachLabel()}의 필요한 안전 정보만 골라 확인할 수 있습니다.</p></div><div class="safety-choice-grid">${ITEMS.map(i=>`<button class="safety-choice" type="button" data-safety-view="${i.key}"><div class="safety-choice-icon">${i.icon}</div><b>${i.label}</b><span>${i.desc}</span></button>`).join("")}</div><p class="safety-modal-helper">실제 입수·통제 여부는 현장 안전요원 안내를 우선하세요.</p>`;inner.querySelectorAll("[data-safety-view]").forEach(b=>b.addEventListener("click",()=>panel(b.dataset.safetyView)));}
    function panel(key){const item=ITEMS.find(i=>i.key===key),card=cards[key];if(!item||!card)return;active=key;const inner=document.querySelector("#safetyModalInner");inner.innerHTML=`<div class="safety-modal-head"><p class="tag">${item.label}</p><h2>${item.label}</h2><p>${beachLabel()}의 ${item.desc} 정보를 확인합니다.</p></div><div id="safetyModalContent" class="safety-modal-content"></div><button id="safetyModalBack" class="safety-modal-back" type="button">← 다른 안전 정보 선택</button>`;inner.querySelector("#safetyModalContent").appendChild(card);inner.querySelector("#safetyModalBack").addEventListener("click",()=>{stash.appendChild(card);choice();});}
    function open(){choice();overlay.hidden=false;document.body.style.overflow="hidden";}
    function close(){if(active!=="overview"&&cards[active])stash.appendChild(cards[active]);overlay.hidden=true;document.body.style.overflow="";active="overview";}
    document.querySelector("#openSafetyModal")?.addEventListener("click",open);document.querySelector("#closeSafetyModal")?.addEventListener("click",close);overlay.addEventListener("click",e=>{if(e.target===overlay)close();});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!overlay.hidden)close();});document.querySelector("#beachSelect")?.addEventListener("change",()=>{if(!overlay.hidden)choice();});
  }
  if(document.readyState==="complete")setup();else window.addEventListener("load",setup,{once:true});
})();

// Robust weather loader: generic Open-Meteo -> JMA fallback -> recent cache.
(() => {
  const BEACH={haeundae:{name:"해운대해수욕장",lat:35.1587,lng:129.1604},gwangalli:{name:"광안리해수욕장",lat:35.1532,lng:129.1186},songjeong:{name:"송정해수욕장",lat:35.1785,lng:129.2016},songdo:{name:"송도해수욕장",lat:35.0767,lng:129.0178}};
  const cacheKey=k=>`beachWeatherCache:v2:${k}`;
  const codeInfo=c=>({0:["☀️","맑음"],1:["🌤️","대체로 맑음"],2:["⛅","구름 조금"],3:["☁️","흐림"],45:["🌫️","안개"],48:["🌫️","안개"],51:["🌦️","이슬비"],53:["🌦️","이슬비"],55:["🌦️","강한 이슬비"],61:["🌧️","비"],63:["🌧️","비"],65:["🌧️","강한 비"],80:["🌦️","소나기"],81:["🌧️","소나기"],82:["⛈️","강한 소나기"],95:["⛈️","뇌우"],96:["⛈️","우박 동반 뇌우"],99:["⛈️","강한 뇌우"]}[c]||["🌡️","날씨 상태 확인"]);
  async function request(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{cache:"no-store",signal:c.signal,headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`weather ${r.status}`);const d=await r.json();if(!d?.current)throw new Error("no current weather");return d.current;}finally{clearTimeout(t);}}
  async function getNow(b){const params=new URLSearchParams({latitude:b.lat,longitude:b.lng,current:"temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m",timezone:"Asia/Seoul",forecast_days:"1"});const urls=[`https://api.open-meteo.com/v1/forecast?${params}`,`https://api.open-meteo.com/v1/jma?${params}`];let last;for(const url of urls){try{return await request(url);}catch(e){last=e;}}throw last||new Error();}
  function readCache(k){try{const d=JSON.parse(localStorage.getItem(cacheKey(k))||"null");return d&&Date.now()-d.savedAt<6*60*60*1000?d.current:null;}catch{return null;}}
  function saveCache(k,current){try{localStorage.setItem(cacheKey(k),JSON.stringify({savedAt:Date.now(),current}));}catch{}}
  function render(b,now,cached=false){const $=s=>document.querySelector(s);if(!$("#weatherBeach"))return;const [emoji,label]=codeInfo(now.weather_code);$("#weatherBeach").textContent=`${b.name} 오늘의 날씨`;$("#weatherIcon").textContent=emoji;$("#weatherTemp").textContent=`${Math.round(now.temperature_2m)}°C`;$("#weatherDesc").textContent=`${label} · 체감 ${Math.round(now.apparent_temperature??now.temperature_2m)}°C`;$("#weatherRain").textContent=`${Number(now.precipitation??0)} mm`;$("#weatherWind").textContent=`${Math.round(now.wind_speed_10m??0)} km/h`;$("#weatherUpdated").textContent=cached?"실시간 연결이 지연되어 최근 정상 수신 정보를 표시 중":"현재 기상 모델 기준 · 자동 갱신";window.updateSafetyIndexFromWeather?.();window.updateConditionAnalysis?.();}
  async function robustWeather(){const k=document.querySelector("#beachSelect")?.value||"haeundae",b=BEACH[k]||BEACH.haeundae,$=s=>document.querySelector(s);if($("#weatherBeach")){$("#weatherBeach").textContent=`${b.name} 오늘의 날씨`;$(("#weatherIcon"))?.textContent;$("#weatherIcon").textContent="…";$("#weatherTemp").textContent="불러오는 중…";$("#weatherDesc").textContent="현재 날씨를 확인하고 있어요.";$("#weatherRain").textContent="–";$("#weatherWind").textContent="–";}try{const now=await getNow(b);saveCache(k,now);render(b,now,false);}catch{const cached=readCache(k);if(cached)render(b,cached,true);else{if($("#weatherIcon"))$("#weatherIcon").textContent="⚠️";if($("#weatherTemp"))$("#weatherTemp").textContent="날씨 확인 필요";if($("#weatherDesc"))$("#weatherDesc").textContent="기상 서버 연결이 지연되고 있어요.";if($("#weatherUpdated"))$("#weatherUpdated").textContent="잠시 후 다시 열면 자동 재시도합니다.";window.updateSafetyIndexFromWeather?.();window.updateConditionAnalysis?.();}}}
  window.loadWeather=robustWeather;
  function init(){robustWeather();document.querySelector("#beachSelect")?.addEventListener("change",()=>setTimeout(robustWeather,30));}
  if(document.readyState==="complete")init();else window.addEventListener("load",init,{once:true});
})();

// Side-panel order and duplicate selected-place cleanup.
(() => {
  function arrange(){const panel=document.querySelector("aside.panel");if(!panel)return;const picker=panel.querySelector(".beach-picker"),cards=[...panel.querySelectorAll(":scope > .card")],currentCard=cards.find(c=>c.querySelector("#locateMe")),env=panel.querySelector(".environment-group"),facility=panel.querySelector(".facility-group"),missing=panel.querySelector(".missing-child-group"),location=panel.querySelector(".location-card"),qr=panel.querySelector(".qr-share-card");if(location)location.style.display="none";[picker,currentCard,env,facility,missing,qr].filter(Boolean).forEach(el=>panel.appendChild(el));}
  if(document.readyState==="complete")arrange();else window.addEventListener("load",()=>setTimeout(arrange,0),{once:true});
})();